import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
decorations = "None"
dynamic_padding = true

[keyboard]
bindings = [
    { action = "Copy", key = "C", mods = "Control|Shift" },
    { action = "Paste", key = "V", mods = "Control|Shift" },
]

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[font]
size = 10.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
