[window]
startup_mode = "Maximized"
decorations = "None"
dynamic_padding = true

[font]
size = 10.0

[keyboard]
bindings = [
    { action = "Copy", key = "C", mods = "Control|Shift" },
    { action = "Paste", key = "V", mods = "Control|Shift" },
]

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]
